spring:
  application:
    name: retrieval-service
  ai:
    ollama:
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: false
  mvc:
    async:
      request-timeout: 5s
server:
  port: 8083
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 20s
