replicaCount: 1

image:
  registry: fra.ocir.io
  namespace: <set-via-deployment>
  name: qa-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8084

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
